### ISSUE TITLE
Can you provide a test example file

### ISSUE THREAD

**Issue by Tanmayp11** [Buddhilive/buddhi-nlp#2]
@Buddhilive  
What is **meta_data.json** file, Is it different from intents.json (file.json)
I'm getting error :  TypeError: Only absolute URLs are supported

` const intents = path.resolve("../utils/intents.json");
 const model = path.resolve("../../lib/buddhi");

buddhi.train(
    "C:\\Users\\abc\\Documents\\test\\src\\utils\\intents.json",
    "C:\\Users\\abc\\Documents\\test\\\test\\lib\\buddhi"
  );

  buddhi.loadModel(model, intents, callbackFunction);
`

Can't we provide local file path, Is it necessary to host file somewhere ?

**Comment by Buddhilive** [comment]
Hi @Tanmayp11 , sorry for the late reply.

There's an typo in your link to the output directory.

`C:\Users\abc\Documents\test\\test\lib\buddhi`

correct it as 

`C:\Users\abc\Documents\test\test\lib\buddhi`

and test again

**Comment by azeez1776** [comment]
@Tanmayp11 How did it go, am trying it now

**Comment by Buddhilive** [comment]
Hi, we migrate the project to a different project today.
Take a look at it.

https://github.com/BerkeliumLabs/nlp-core/
